"""empty message

Revision ID: 5cfbae1c4fa7
Revises: 08958b89f110
Create Date: 2022-02-01 18:31:59.688064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfbae1c4fa7'
down_revision = '08958b89f110'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('admins', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('coaches', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('coaches', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('coaches', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('equipments', 'helmet_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'shoulder_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'body_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'leg_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('players', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('players', 'status',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('stadiums', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('stadiums', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('teams', 'symbol',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('teams', 'stadium_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'stadium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'symbol',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('stadiums', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('stadiums', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('players', 'status',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('players', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'leg_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'body_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'shoulder_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'helmet_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('coaches', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coaches', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('coaches', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('admins', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('admins', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###
