"""empty message

Revision ID: 33a2dc242c12
Revises: 5cfbae1c4fa7
Create Date: 2022-02-01 19:17:06.837513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a2dc242c12'
down_revision = '5cfbae1c4fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('admins', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('coaches', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('coaches', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'helmet_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'shoulder_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'body_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('equipments', 'leg_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('players', 'status',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('stadiums', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('stadiums', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('teams', 'symbol',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'symbol',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('teams', 'city',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('stadiums', 'capacity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('stadiums', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('players', 'status',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('players', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'leg_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'body_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'shoulder_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('equipments', 'helmet_size',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('coaches', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('coaches', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('admins', 'work_position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('admins', 'name',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    # ### end Alembic commands ###
