"""empty message

Revision ID: 08958b89f110
Revises: 
Create Date: 2022-02-01 18:25:36.059488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08958b89f110'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('work_position', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('stadiums',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('merchandise', sa.String(length=128), nullable=True),
    sa.Column('menu', sa.String(length=128), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=128), nullable=False),
    sa.Column('stadium_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['stadium_id'], ['stadiums.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('work_position', sa.String(length=128), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('work_position', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=128), nullable=False),
    sa.Column('experience', sa.String(length=128), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('helmet_size', sa.String(length=128), nullable=False),
    sa.Column('shoulder_size', sa.String(length=128), nullable=False),
    sa.Column('body_size', sa.String(length=128), nullable=False),
    sa.Column('leg_size', sa.String(length=128), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('manages',
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('coach_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manages')
    op.drop_table('equipments')
    op.drop_table('players')
    op.drop_table('coaches')
    op.drop_table('teams')
    op.drop_table('stadiums')
    op.drop_table('admins')
    # ### end Alembic commands ###
