"""empty message

Revision ID: 9292a41e40c5
Revises: 8dd0d868d92e
Create Date: 2022-02-01 19:46:07.985255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9292a41e40c5'
down_revision = '8dd0d868d92e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coaches', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'stadium_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('teams', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'admin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('teams', 'stadium_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coaches', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
